apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: stocktrader-operator
  namespace: openshift-operators 
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: stocktrader-operator
  source: stocktrader-catalog
  sourceNamespace: openshift-marketplace
  startingCSV: stocktrader-operator.v0.2.0
