apiVersion: operators.ibm.com/v1
kind: StockTrader
metadata:
  name: ceh
  namespace: stocktrader
spec:
  global:
    auth: basic
    healthCheck: true
    istio: false
    ingress: false
    istioNamespace: mesh
    route: true
    traceSpec: "*=info"
    jsonLogging: false
    disableLogFiles: false
    monitoring: true
    secretName: 'ceh-credentials'
    externalSecret: true
    specifyCerts: true
    certs: |
      -----BEGIN CERTIFICATE-----
      MIINlTCCDH2gAwIBAgIQA1OXnI5PL8iJCejmERiIHTANBgkqhkiG9w0BAQsFADBP
      MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMSkwJwYDVQQDEyBE
      aWdpQ2VydCBUTFMgUlNBIFNIQTI1NiAyMDIwIENBMTAeFw0yMTAyMjIwMDAwMDBa
      Fw0yMjAzMjUyMzU5NTlaMIGnMQswCQYDVQQGEwJVUzEPMA0GA1UECBMGS2Fuc2Fz
      MRYwFAYDVQQHEw1PdmVybGFuZCBQYXJrMTQwMgYDVQQKEytJTlRFUk5BVElPTkFM
      IEJVU0lORVNTIE1BQ0hJTkVTIENPUlBPUkFUSU9OMTkwNwYDVQQDDDAqLmJwZTYw
      cGJkMDFvaW5nZTRwc2QwLmRhdGFiYXNlcy5hcHBkb21haW4uY2xvdWQwggEiMA0G
      CSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCv0ui2hmxME58o+u6At34nSBXkcgqM
      LYY2T0gjXezi85mvdEpwwQhl0jqdTOZYuIIpOYmpslEWB709lzhyWGqgnKP+DasE
      ZTJHpKLeangLW84jWSpvVeyZ+yR4XTDntaTPysA0MB7UN3oeG5JhHTQOTjn12sA7
      DIF5G5pfRBFK5gZFD74RO7tPsbpMeWx+99Lf4uHLvwkNziHPNshhVCRtclPKONv0
      M91wXiIcsTBXizqkspfldVtBAE2+c/HhJiM8mBzflFAAvtMgRxNHuxfiKphXgO1N
      1mRbmzrzS4e3ibbb2Zf/SIgFD55uHq6h8vsmElFQTB44Cg0zNpaxrkMlAgMBAAGj
      ggoSMIIKDjAfBgNVHSMEGDAWgBS3a6LqqKqEjHnqtNoPmLLFlXa59DAdBgNVHQ4E
      FgQUGCOFTuIXJJa/xOcEc5qlhEk5VvUwggc5BgNVHREEggcwMIIHLIIwKi5icGU2
      MHBiZDAxb2luZ2U0cHNkMC5kYXRhYmFzZXMuYXBwZG9tYWluLmNsb3VkgjgqLmJw
      ZTYwcGJkMDFvaW5nZTRwc2QwLnByaXZhdGUuZGF0YWJhc2VzLmFwcGRvbWFpbi5j
      bG91ZII4Ki5iczJpcGE3dzB1djl0c29taTlpZy5wcml2YXRlLmRhdGFiYXNlcy5h
      cHBkb21haW4uY2xvdWSCMCouYnMyaXBhN3cwdXY5dHNvbWk5aWcuZGF0YWJhc2Vz
      LmFwcGRvbWFpbi5jbG91ZII4Ki5iczJpcG1idDBpZmxkOHJkYzl1MC5wcml2YXRl
      LmRhdGFiYXNlcy5hcHBkb21haW4uY2xvdWSCMCouYnMyaXBtYnQwaWZsZDhyZGM5
      dTAuZGF0YWJhc2VzLmFwcGRvbWFpbi5jbG91ZII4Ki5iczJpbzkwbDA4a3FiMW9k
      OGxjZy5wcml2YXRlLmRhdGFiYXNlcy5hcHBkb21haW4uY2xvdWSCMCouYnMyaW85
      MGwwOGtxYjFvZDhsY2cuZGF0YWJhc2VzLmFwcGRvbWFpbi5jbG91ZII4Ki5icnQ5
      ZDA0ZjBjbXFlYjh1Nzc0MC5wcml2YXRlLmRhdGFiYXNlcy5hcHBkb21haW4uY2xv
      dWSCMCouYnJ0OWQwNGYwY21xZWI4dTc3NDAuZGF0YWJhc2VzLmFwcGRvbWFpbi5j
      bG91ZII4Ki5iczJpcHI4czA3YjdiZ20xdGE4MC5wcml2YXRlLmRhdGFiYXNlcy5h
      cHBkb21haW4uY2xvdWSCMCouYnMyaXByOHMwN2I3YmdtMXRhODAuZGF0YWJhc2Vz
      LmFwcGRvbWFpbi5jbG91ZII4Ki5idHY1M2wwZjA1NDE4MzlvMXY0MC5wcml2YXRl
      LmRhdGFiYXNlcy5hcHBkb21haW4uY2xvdWSCMCouYnR2NTNsMGYwNTQxODM5bzF2
      NDAuZGF0YWJhc2VzLmFwcGRvbWFpbi5jbG91ZII4Ki5idWdxOXR1dzA4MW52ZTlu
      ZTE2MC5wcml2YXRlLmRhdGFiYXNlcy5hcHBkb21haW4uY2xvdWSCMCouYnVncTl0
      dXcwODFudmU5bmUxNjAuZGF0YWJhc2VzLmFwcGRvbWFpbi5jbG91ZII4Ki5idHYx
      cmVqZjBydGtwZDE2MnJnMC5wcml2YXRlLmRhdGFiYXNlcy5hcHBkb21haW4uY2xv
      dWSCMCouYnR2MXJlamYwcnRrcGQxNjJyZzAuZGF0YWJhc2VzLmFwcGRvbWFpbi5j
      bG91ZII4Ki5idHY1cDVmZDBjdDYzODNxZnRkZy5wcml2YXRlLmRhdGFiYXNlcy5h
      cHBkb21haW4uY2xvdWSCMCouYnR2NXA1ZmQwY3Q2MzgzcWZ0ZGcuZGF0YWJhc2Vz
      LmFwcGRvbWFpbi5jbG91ZII4Ki5idHY0OGpjdzBwZGQ2ZjRubWd2Zy5wcml2YXRl
      LmRhdGFiYXNlcy5hcHBkb21haW4uY2xvdWSCMCouYnR2NDhqY3cwcGRkNmY0bm1n
      dmcuZGF0YWJhc2VzLmFwcGRvbWFpbi5jbG91ZII4Ki5idHYyczN0ZjBrbTR1c3Bv
      MXYzMC5wcml2YXRlLmRhdGFiYXNlcy5hcHBkb21haW4uY2xvdWSCMCouYnR2MnMz
      dGYwa200dXNwbzF2MzAuZGF0YWJhc2VzLmFwcGRvbWFpbi5jbG91ZII4Ki5idW5r
      bGFlZjBqazM0aXVmNml2Zy5wcml2YXRlLmRhdGFiYXNlcy5hcHBkb21haW4uY2xv
      dWSCMCouYnVua2xhZWYwamszNGl1ZjZpdmcuZGF0YWJhc2VzLmFwcGRvbWFpbi5j
      bG91ZII4Ki5idjdjM282ZDB2ZmhydTNucGRzMC5wcml2YXRlLmRhdGFiYXNlcy5h
      cHBkb21haW4uY2xvdWSCMCouYnY3YzNvNmQwdmZocnUzbnBkczAuZGF0YWJhc2Vz
      LmFwcGRvbWFpbi5jbG91ZII4Ki5idjdlOHJiZjBzaHNsYm8wa3JzZy5wcml2YXRl
      LmRhdGFiYXNlcy5hcHBkb21haW4uY2xvdWSCMCouYnY3ZThyYmYwc2hzbGJvMGty
      c2cuZGF0YWJhc2VzLmFwcGRvbWFpbi5jbG91ZIIwKi5jMDh1dDA3bDBwaW5jcGRs
      ZTg5MC5kYXRhYmFzZXMuYXBwZG9tYWluLmNsb3VkgjgqLmMwOHV0MDdsMHBpbmNw
      ZGxlODkwLnByaXZhdGUuZGF0YWJhc2VzLmFwcGRvbWFpbi5jbG91ZIIwKi5icjM5
      YjRrZDBuaGNjM2pmZmJ0MC5kYXRhYmFzZXMuYXBwZG9tYWluLmNsb3VkgjgqLmJy
      MzliNGtkMG5oY2MzamZmYnQwLnByaXZhdGUuZGF0YWJhc2VzLmFwcGRvbWFpbi5j
      bG91ZDAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUF
      BwMCMIGLBgNVHR8EgYMwgYAwPqA8oDqGOGh0dHA6Ly9jcmwzLmRpZ2ljZXJ0LmNv
      bS9EaWdpQ2VydFRMU1JTQVNIQTI1NjIwMjBDQTEuY3JsMD6gPKA6hjhodHRwOi8v
      Y3JsNC5kaWdpY2VydC5jb20vRGlnaUNlcnRUTFNSU0FTSEEyNTYyMDIwQ0ExLmNy
      bDA+BgNVHSAENzA1MDMGBmeBDAECAjApMCcGCCsGAQUFBwIBFhtodHRwOi8vd3d3
      LmRpZ2ljZXJ0LmNvbS9DUFMwfQYIKwYBBQUHAQEEcTBvMCQGCCsGAQUFBzABhhho
      dHRwOi8vb2NzcC5kaWdpY2VydC5jb20wRwYIKwYBBQUHMAKGO2h0dHA6Ly9jYWNl
      cnRzLmRpZ2ljZXJ0LmNvbS9EaWdpQ2VydFRMU1JTQVNIQTI1NjIwMjBDQTEuY3J0
      MAwGA1UdEwEB/wQCMAAwggEDBgorBgEEAdZ5AgQCBIH0BIHxAO8AdQApeb7wnjk5
      IfBWc59jpXflvld9nGAK+PlNXSZcJV3HhAAAAXfLZUkOAAAEAwBGMEQCIHWszBBW
      UaAnNbPWtNWo/MYCgUOmmfKOST4TthOgRruBAiAHrcR1a2K0VJstbNaYp+8dOhfM
      rGiKafcmjyvvPAkG/wB2AFGjsPX9AXmcVm24N3iPDKR6zBsny/eeiEKaDf7UiwXl
      AAABd8tlSWMAAAQDAEcwRQIgS1zYbxK0X5gVyiLbOTGL9EbmmxKwaLbxkqkg14aj
      reACIQDgRPZZQvZIW3V0tTXDek5WXOYce2Wb5oXhy4gGKvKytTANBgkqhkiG9w0B
      AQsFAAOCAQEAQnv7zROg6HtUM9/JvctOxnpPCKZlk7jFsjFvoL2rAXebg5et08uK
      uufC8lJ1+jO/9q4T+8ugd6c65SVOdG3EnL4wTv+pXcnbn55nRqtXs3SgyJcusdyx
      3XgTU8LYE9Ig7fIboveIeeEfTnE4XUBH3E63x7D74QYWRBMtJyTsZgoLr8T2FvYk
      euAsFH0gBe5PBUrsXMfF9z4J7Z+twM49cYqZf5gi9Ewl8Ikm7NZlPkJIxp+/T3NV
      kR1bArTyi7+7aBbP7DCSd5prmHPj3LEsXdPD0GtpfsRVjvPLbPNtyYylpt2CGKFg
      zngDAqDez0xH+lXeXo3l1CwdMllRctPk2A==
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
      MIIDrzCCApegAwIBAgIQCDvgVpBCRrGhdWrJWZHHSjANBgkqhkiG9w0BAQUFADBh
      MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
      d3cuZGlnaWNlcnQuY29tMSAwHgYDVQQDExdEaWdpQ2VydCBHbG9iYWwgUm9vdCBD
      QTAeFw0wNjExMTAwMDAwMDBaFw0zMTExMTAwMDAwMDBaMGExCzAJBgNVBAYTAlVT
      MRUwEwYDVQQKEwxEaWdpQ2VydCBJbmMxGTAXBgNVBAsTEHd3dy5kaWdpY2VydC5j
      b20xIDAeBgNVBAMTF0RpZ2lDZXJ0IEdsb2JhbCBSb290IENBMIIBIjANBgkqhkiG
      9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4jvhEXLeqKTTo1eqUKKPC3eQyaKl7hLOllsB
      CSDMAZOnTjC3U/dDxGkAV53ijSLdhwZAAIEJzs4bg7/fzTtxRuLWZscFs3YnFo97
      nh6Vfe63SKMI2tavegw5BmV/Sl0fvBf4q77uKNd0f3p4mVmFaG5cIzJLv07A6Fpt
      43C/dxC//AH2hdmoRBBYMql1GNXRor5H4idq9Joz+EkIYIvUX7Q6hL+hqkpMfT7P
      T19sdl6gSzeRntwi5m3OFBqOasv+zbMUZBfHWymeMr/y7vrTC0LUq7dBMtoM1O/4
      gdW7jVg/tRvoSSiicNoxBN33shbyTApOB6jtSj1etX+jkMOvJwIDAQABo2MwYTAO
      BgNVHQ8BAf8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUA95QNVbR
      TLtm8KPiGxvDl7I90VUwHwYDVR0jBBgwFoAUA95QNVbRTLtm8KPiGxvDl7I90VUw
      DQYJKoZIhvcNAQEFBQADggEBAMucN6pIExIK+t1EnE9SsPTfrgT1eXkIoyQY/Esr
      hMAtudXH/vTBH1jLuG2cenTnmCmrEbXjcKChzUyImZOMkXDiqw8cvpOp/2PV5Adg
      06O/nVsJ8dWO41P0jmP6P6fbtGbfYmbW0W5BjfIttep3Sp+dWOIrWcBAI+0tKIJF
      PnlUkiaY4IBIqDfv8NZ5YBberOgOzW6sRBc4L0na4UU+Krk2U886UAb3LujEV0ls
      YSEY1QSteDwsOoBrp+uvFRTp2InBuThs4pFsiv9kuXclVzDAGySj4dzp30d8tbQk
      CAUw7C29C79Fv1C5qfPrmAESrciIxpg0X40KPMbp1ZWVbd4=
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
      MIIElDCCA3ygAwIBAgIQAf2j627KdciIQ4tyS8+8kTANBgkqhkiG9w0BAQsFADBh
      MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
      d3cuZGlnaWNlcnQuY29tMSAwHgYDVQQDExdEaWdpQ2VydCBHbG9iYWwgUm9vdCBD
      QTAeFw0xMzAzMDgxMjAwMDBaFw0yMzAzMDgxMjAwMDBaME0xCzAJBgNVBAYTAlVT
      MRUwEwYDVQQKEwxEaWdpQ2VydCBJbmMxJzAlBgNVBAMTHkRpZ2lDZXJ0IFNIQTIg
      U2VjdXJlIFNlcnZlciBDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEB
      ANyuWJBNwcQwFZA1W248ghX1LFy949v/cUP6ZCWA1O4Yok3wZtAKc24RmDYXZK83
      nf36QYSvx6+M/hpzTc8zl5CilodTgyu5pnVILR1WN3vaMTIa16yrBvSqXUu3R0bd
      KpPDkC55gIDvEwRqFDu1m5K+wgdlTvza/P96rtxcflUxDOg5B6TXvi/TC2rSsd9f
      /ld0Uzs1gN2ujkSYs58O09rg1/RrKatEp0tYhG2SS4HD2nOLEpdIkARFdRrdNzGX
      kujNVA075ME/OV4uuPNcfhCOhkEAjUVmR7ChZc6gqikJTvOX6+guqw9ypzAO+sf0
      /RR3w6RbKFfCs/mC/bdFWJsCAwEAAaOCAVowggFWMBIGA1UdEwEB/wQIMAYBAf8C
      AQAwDgYDVR0PAQH/BAQDAgGGMDQGCCsGAQUFBwEBBCgwJjAkBggrBgEFBQcwAYYY
      aHR0cDovL29jc3AuZGlnaWNlcnQuY29tMHsGA1UdHwR0MHIwN6A1oDOGMWh0dHA6
      Ly9jcmwzLmRpZ2ljZXJ0LmNvbS9EaWdpQ2VydEdsb2JhbFJvb3RDQS5jcmwwN6A1
      oDOGMWh0dHA6Ly9jcmw0LmRpZ2ljZXJ0LmNvbS9EaWdpQ2VydEdsb2JhbFJvb3RD
      QS5jcmwwPQYDVR0gBDYwNDAyBgRVHSAAMCowKAYIKwYBBQUHAgEWHGh0dHBzOi8v
      d3d3LmRpZ2ljZXJ0LmNvbS9DUFMwHQYDVR0OBBYEFA+AYRyCMWHVLyjnjUY4tCzh
      xtniMB8GA1UdIwQYMBaAFAPeUDVW0Uy7ZvCj4hsbw5eyPdFVMA0GCSqGSIb3DQEB
      CwUAA4IBAQAjPt9L0jFCpbZ+QlwaRMxp0Wi0XUvgBCFsS+JtzLHgl4+mUwnNqipl
      5TlPHoOlblyYoiQm5vuh7ZPHLgLGTUq/sELfeNqzqPlt/yGFUzZgTHbO7Djc1lGA
      8MXW5dRNJ2Srm8c+cftIl7gzbckTB+6WohsYFfZcTEDts8Ls/3HB40f/1LkAtDdC
      2iDJ6m6K7hQGrn2iWZiIqBtvLfTyyRRfJs8sjX7tN8Cp1Tm5gr8ZDOo0rwAhaPit
      c+LJMto4JQtV05od8GiG7S5BNO98pVAdvzr508EIDObtHopYJeS4d60tbvVS3bR0
      j6tJLp07kzQoH3jOlOrHvdPJbRzeXDLz
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
      MIIDHTCCAgWgAwIBAgIUL5g6t1HmNOt8OOqUWyuQZeWsrUAwDQYJKoZIhvcNAQEL
      BQAwHjEcMBoGA1UEAwwTSUJNIENsb3VkIERhdGFiYXNlczAeFw0xODExMjExMTQ3
      MjdaFw0yODExMTgxMTQ3MjdaMB4xHDAaBgNVBAMME0lCTSBDbG91ZCBEYXRhYmFz
      ZXMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC3hxfosYeXdmrQRHlU
      vMg91IWSCuGZ16RbHbZ2p62SEUfBJemr4MkTr48YZTfiTCZjckWWGlBlvUYr0cYY
      KM3OPtkhk3lmkAQlJcMCPfiF2+mBxAUqrIibCgmQijylRJW4sEFQgSbrXewDywEd
      8JUgm+82DwLYy6vnkKJjzcUZk5OKS1Uv7w0pHUtUMtNLaSyKksDdE9d9sj6lWTFJ
      W9CyXCp5iffJ97oewIh47nIFYU5D5MptCDYr6wifOWvhiduYD6WMR7wDgLMv/ra9
      Zt4nt7MYglRmKnO77DZI5Y9lT4gw4FiU0k65aWnXrk+1DZ4jqFdWk3VpoXhA0IuX
      ZMbPAgMBAAGjUzBRMB0GA1UdDgQWBBQYWTX4dsUL3/LnQAXQLLzh46yDATAfBgNV
      HSMEGDAWgBQYWTX4dsUL3/LnQAXQLLzh46yDATAPBgNVHRMBAf8EBTADAQH/MA0G
      CSqGSIb3DQEBCwUAA4IBAQAPwYrOIQMEreNuHY/68lFJimB6GCinGsJw8YIBBQwA
      tdJMOXU8bXGrEHEuZ6Qaho7Q5dV2bB6GVKTMqhSEdrvuyxKniQ90jdkQSk2VHhDe
      H+6i04hA9TkKT6ooLwMPc1LYYzqDljEkfKlLIPWCkOAozD3cyc26pV/35nG7WzAF
      xw7S3jAyB3WcJDlWlSWGTn58w3EHxzVXvKT6Y9eAdKp4SjUHyVFsL5xtSyjH8zpF
      pZKK8wWNUwgWQ66MNh8Ckq732JZ+so6RAfb4BbNj45I3s9fuZSYlvjkc5/+da3Ck
      Rp6anX5N6yIrzhVmAgefjQdBztYzdfPhsJBkS/TDnRmk
      -----END CERTIFICATE-----
  database:
    kind: postgres
    db: bludb
    host: dbaas907.hyperp-dbaas.cloud.ibm.com
    port: 30139
    ssl: true
  jwt:
    audience: stock-trader
    issuer: http://stock-trader.ibm.com
  kafka:
    address: broker-1-63pby2k66qq17x9z.kafka.svc01.us-south.eventstreams.cloud.ibm.com:9093,broker-4-63pby2k66qq17x9z.kafka.svc01.us-south.eventstreams.cloud.ibm.com:9093,broker-3-63pby2k66qq17x9z.kafka.svc01.us-south.eventstreams.cloud.ibm.com:9093,broker-0-63pby2k66qq17x9z.kafka.svc01.us-south.eventstreams.cloud.ibm.com:9093,broker-2-63pby2k66qq17x9z.kafka.svc01.us-south.eventstreams.cloud.ibm.com:9093,broker-5-63pby2k66qq17x9z.kafka.svc01.us-south.eventstreams.cloud.ibm.com:9093
    accountTopic: account
    historyTopic: history
    portfolioTopic: portfolio
  looper:
    enabled: false
    replicas: 1
    autoscale: false
    maxReplicas: 10
    cpuThreshold: 75
    image:
      repository: ibmstocktrader/looper
      tag: latest
    url: http://{{ .Release.Name }}-looper-service:9080/looper
  broker:
    replicas: 1
    autoscale: false
    maxReplicas: 10
    cpuThreshold: 75
    image:
      repository: ibmstocktrader/broker
      tag: latest
    url: http://{{ .Release.Name }}-broker-service:9080/broker
  brokerCQRS:
    enabled: false
    replicas: 1
    autoscale: false
    maxReplicas: 10
    cpuThreshold: 75
    image:
      repository: ibmstocktrader/broker-cqrs
      tag: latest
    url: http://{{ .Release.Name }}-broker-cqrs-service:9080/brokerCQRS
  account:
    enabled: false
    replicas: 1
    autoscale: false
    maxReplicas: 10
    cpuThreshold: 75
    image:
      repository: ibmstocktrader/account
      tag: latest
    url: http://{{ .Release.Name }}-account-service:9080/account
  messaging:
    enabled: false
    replicas: 1
    autoscale: false
    maxReplicas: 10
    cpuThreshold: 75
    image:
      repository: ibmstocktrader/messaging
      tag: latest
    notification:
      url: http://{{ .Release.Name }}-notification-service:9080/notification
  cloudant:
    id: n/a
    password: n/a
    url: https://878ff489-3ab9-4d2d-86db-016f19864439-bluemix:58819704e70bb791d81eb09847e8da2d69cb492ed4fe35a4e682e38c0785e5e9@878ff489-3ab9-4d2d-86db-016f19864439-bluemix.cloudantnosqldb.appdomain.cloud
    database: account
    collector: evidence
  collector:
    enabled: false
    replicas: 1
    autoscale: false
    maxReplicas: 10
    cpuThreshold: 75
    image:
      repository: ibmstocktrader/collector
      tag: latest
    url: http://{{ .Release.Name }}-collector-service:9080/collector
  ldap:
    baseDN: o=ibm.com
    host: bluepages.ibm.com
    port: 389
    realm: BluePages
  mongo:
    authDB: admin
    database: ibmclouddb
    ip: 915ce0b3-e08f-4aec-b58a-47e80442c6b4-0.blijs0dd0dcr4f55oehg.databases.appdomain.cloud
    port: 30926
    user: n/a
    password: n/a
  mq:
    channel: CLOUD.APP.SVRCONN
    host: qm1-4565.qm.us-south.mq.appdomain.cloud
    id: n/a
    password: n/a
    port: 30341
    queue: LoyaltyLevelChange
    queueManager: QM1
  notificationSlack:
    enabled: false
    replicas: 1
    autoscale: false
    maxReplicas: 10
    cpuThreshold: 75
    image:
      repository: ibmstocktrader/notification-slack
      tag: latest
  notificationTwitter:
    enabled: false
    replicas: 1
    autoscale: false
    maxReplicas: 10
    cpuThreshold: 75
    image:
      repository: ibmstocktrader/notification-twitter
      tag: latest
  odm:
    id: n/a
    password: n/a
    url: https://odm-connect-cp4a.devops-prereqs-44-a01ee4194ed985a1e32b1d96fd4ae346-0000.us-east.containers.appdomain.cloud/DecisionService/rest/v1/ICP_Trader_Dev_1/determineLoyalty
  oidc:
    clientId: <your client id>
    clientSecret: <your client secret>
    discoveryUrl: <your discovery url>
  openwhisk:
    id: n/a
    password: n/a
    url: https://openwhisk.ng.bluemix.net/api/v1/namespaces/jalcorn%40us.ibm.com_dev/actions/PostLoyaltyLevelToSlack
  portfolio:
    replicas: 1
    autoscale: false
    maxReplicas: 10
    cpuThreshold: 75
    image:
      repository: ibmstocktrader/portfolio
      tag: latest
    url: http://{{ .Release.Name }}-portfolio-service:9080/portfolio
  redis:
    cacheInterval: 60
  s3:
    enabled: false
    bucket: stock-trader
    location: us
    endpointUrl: https://s3.us-east.cloud-object-storage.appdomain.cloud
    resourceInstanceId: >-
      crn:v1:bluemix:public:cloud-object-storage:global:a/b71ac2564ef0b98f1032d189795994dc:f7e4281d-a7f2-4923-8e6b-07f99ac93bbd::
  stockQuote:
    replicas: 1
    autoscale: false
    maxReplicas: 10
    cpuThreshold: 75
    apiConnect: https://api.us.apiconnect.ibmcloud.com/jalcornusibmcom-dev/sb/stocks
    iexApiKey: <your IEX API key>
    iexTrading: https://cloud.iexapis.com/stable/stock
    image:
      repository: ibmstocktrader/stock-quote
      tag: latest
    url: http://{{ .Release.Name }}-stock-quote-service:9080/stock-quote
  tradeHistory:
    enabled: false
    replicas: 1
    autoscale: false
    maxReplicas: 10
    cpuThreshold: 75
    image:
      repository: ibmstocktrader/trade-history
      tag: latest
    url: http://{{ .Release.Name }}-trade-history-service:9080/trade-history
  trader:
    enabled: true
    replicas: 1
    autoscale: false
    maxReplicas: 10
    cpuThreshold: 75
    image:
      repository: quay.io/gas_stocktrader/trader-poc
      tag: de5403c3adc6bc98740b32e2871a9c230aa6cfff
  tradr:
    enabled: false
    replicas: 1
    autoscale: false
    maxReplicas: 10
    cpuThreshold: 75
    image:
      repository: ibmstocktrader/tradr
      tag: latest
  twitter:
    accessToken: n/a
    accessTokenSecret: n/a
    consumerKey: n/a
    consumerSecret: n/a
  watson:
    url: https://api.us-south.tone-analyzer.watson.cloud.ibm.com/instances/195be178-5f78-467f-8355-99ee5772f4c2/v3/tone?version=2017-09-21&sentences=false
