apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: stocktrader-catalog
  namespace: openshift-marketplace 
spec:
  sourceType: grpc
  image: docker.io/ibmstocktrader/stocktrader-operator-catalog:v0.2.0
  displayName: StockTrader Catalog
  publisher: IBM
  updateStrategy:
    registryPoll: 
      interval: 30m
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: stocktrader-operator
  namespace: openshift-operators 
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: stocktrader-operator
  source: stocktrader-catalog
  sourceNamespace: openshift-marketplace
  startingCSV: stocktrader-operator.v0.2.0
